exports.ERROR_MESSAGE = {
    SOMETHING_WENT_WRONG: 'Something went wrong',
    INVALID_REQUEST: 'Invalid Request',
    INVALID_DATA: 'Invalid Data',
    INVALID_EMAIL: 'Invalid Email',
    INVALID_PHONE: 'Invalid Phone',
    INVALID_PASSWORD: 'Invalid Password',
    INVALID_OTP: 'Invalid OTP',
    INVALID_ADDRESS: 'Invalid Address',
    EMAIL_ALREADY_EXISTS: 'Email Already Exists',
};

exports.SUCCESS_MESSAGE={
    USER_CREATED_SUCCESSFULLY:'User Created Successfully',
    DATA_FETCHED_SUCCESSFULLY:'Data Fetched Successfully',
    DATA_SAVED_SUCCESSFULLY:'Data Saved Successfully',
    DATA_UPDATED_SUCCESSFULLY:'Data Updated Successfully',
    DATA_DELETED_SUCCESSFULLY:'Data Deleted Successfully',
    DATA_NOT_FOUND:'Data Not Found',
    DATA_ALREADY_EXISTS:'Data Already Exists',
    DATA_NOT_SAVED:'Data Not Saved',
    DATA_NOT_UPDATED:'Data Not Updated',
    DATA_NOT_DELETED:'Data Not Deleted',
    DATA_NOT_FETCHED:'Data Not Fetched',
    DATA_NOT_FOUND:'Data Not Found',
    DATA_NOT_EXISTS:'Data Not Exists',
    DATA_NOT_VERIFIED:'Data Not Verified',
    SUCCESSFULLY_REGISTERED:'Successfully Registered',
    SUCCESSFULLY_LOGGED_IN:'Successfully Logged In',
    SUCCESSFULLY_LOGGED_OUT:'Successfully Logged Out',
    SUCCESSFULLY_UPDATED:'Successfully Updated',
    SUCCESSFULLY_DELETED:'Successfully Deleted',
    SUCCESSFULLY_ADDED:'Successfully Added',
    SUCCESSFULLY_FETCHED:'Successfully Fetched',
    SUCCESSFULLY_SENT_OTP:'Successfully Sent OTP',
    SUCCESSFULLY_VERIFIED_OTP:'Successfully Verified OTP',
    SUCCESSFULLY_CHANGED_PASSWORD:'XXXXXXXXXXXX Changed Password',
    SUCCESSFULLY_UPDATED_PROFILE:'Successfully Updated Profile',
    SUCCESSFULLY_UPDATED_PASSWORD:'XXXXXXXXXXXX Updated Password',
    SUCCESSFULLY_UPDATED_EMAIL:'Successfully Updated Email',
    SUCCESSFULLY_UPDATED_PHONE:'Successfully Updated Phone',
    SUCCESSFULLY_UPDATED_ADDRESS:'Successfully Updated Address',
    SUCCESSFULLY_UPDATED_CITY:'Successfully Updated City',
    SUCCESSFULLY_UPDATED_STATE:'Successfully Updated State',
    SUCCESSFULLY_UPDATED_COUNTRY:'Successfully Updated Country',
    SUCCESSFULLY_UPDATED_PINCODE:'Successfully Updated Pincode',
    SUCCESSFULLY_UPDATED_DOB:'Successfully Updated DOB',
    SUCCESSFULLY_UPDATED_GENDER:'Successfully Updated Gender',
    SUCCESSFULLY_UPDATED_BIO:'Successfully Updated Bio',
    SUCCESSFULLY_UPDATED_PROFILE_PICTURE:'Successfully Updated Profile Picture',
    SUCCESSFULLY_UPDATED_COVER_PICTURE:'Successfully Updated Cover Picture',
    SUCCESSFULLY_UPDATED_PROFILE_PICTURE_AND_COVER_PICTURE:'Successfully Updated Profile Picture and Cover Picture',
    SUCCESSFULLY_UPDATED_PROFILE_PICTURE_AND_COVER_PICTURE:'Successfully Updated Profile Picture and Cover Picture',
    SUCCESSFULLY_UPDATED_PROFILE_PICTURE_AND_COVER_PICTURE:'Successfully Updated Profile Picture and Cover Picture',
    SUCCESSFULLY_UPDATED_PROFILE_PICTURE_AND_COVER_PICTURE:'Successfully Updated Profile Picture and Cover Picture',
    SUCCESSFULLY_UPDATED_PROFILE_PICTURE_AND_COVER_PICTURE:'Successfully Updated Profile Picture and Cover Picture',
}